spring.application.name=abstracts

spring.config.import=optional:file:./development.properties

spring.datasource.url=jdbc:mysql://localhost/abstracts
spring.datasource.username=abstracts
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false