package jp.neuroinf.abstracts.controller;

import static jp.neuroinf.abstracts.support.TestData.login;
import static org.hamcrest.Matchers.containsString;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.web.servlet.MockMvc;

import jp.neuroinf.abstracts.component.TimestampSigner;
import jp.neuroinf.abstracts.entity.Account;
import jp.neuroinf.abstracts.repository.AccountRepository;
import jp.neuroinf.abstracts.support.IntegrationTest;
import jp.neuroinf.abstracts.support.TestData;

@IntegrationTest
@ExtendWith(OutputCaptureExtension.class)
class UsersApiTest {

  @Autowired
  private MockMvc mockMvc;

  @Autowired
  private TestData testData;

  @Autowired
  private AccountRepository accountRepository;

  @Autowired
  private PasswordEncoder passwordEncoder;

  @Autowired
  private TimestampSigner timestampSigner;

  private boolean hasPassword(Account account, String password) {
    return this.passwordEncoder.matches(password,
        this.accountRepository.findFirstByUuid(account.getUuid()).getPassword());
  }

  @Test
  void currentUser() throws Exception {
    Account account = this.testData.account("user@example.com");
    Account admin = this.testData.admin();
    this.mockMvc.perform(get("/api/users/current"))
        .andExpect(status().isUnauthorized());
    this.mockMvc.perform(get("/api/users/current").with(login(account)))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.mail").value("user@example.com"))
        .andExpect(jsonPath("$.isAdmin").value(false))
        .andExpect(jsonPath("$.password").doesNotExist());
    this.mockMvc.perform(get("/api/users/current").with(login(admin)))
        .andExpect(jsonPath("$.isAdmin").value(true));
  }

  @Test
  void existsRequiresLogin() throws Exception {
    Account account = this.testData.account("user@example.com");
    this.mockMvc.perform(get("/api/users/exists").param("email", "user@example.com"))
        .andExpect(status().isUnauthorized());
    this.mockMvc.perform(get("/api/users/exists").param("email", "user@example.com").with(login(account)))
        .andExpect(status().isOk());
    this.mockMvc.perform(get("/api/users/exists").param("email", "nobody@example.com").with(login(account)))
        .andExpect(status().isNotFound());
  }

  @Test
  void passwordResetRequestMailsALink(CapturedOutput output) throws Exception {
    this.testData.account("user@example.com");
    this.mockMvc.perform(post("/api/users/password/reset/request").param("email", "user@example.com").with(csrf()))
        .andExpect(status().isOk());
    assertTrue(output.getOut().contains("Request to reset password"));
    assertTrue(output.getOut().contains("http://localhost:8080/resetpassword?token="));
    this.mockMvc.perform(post("/api/users/password/reset/request").param("email", "nobody@example.com")
        .with(csrf()))
        .andExpect(status().isNotFound());
  }

  @Test
  void passwordResetMailsANewPassword(CapturedOutput output) throws Exception {
    Account account = this.testData.account("user@example.com");
    String token = this.timestampSigner.sign("user@example.com");
    this.mockMvc.perform(post("/api/users/password/reset").param("token", token).with(csrf()))
        .andExpect(status().isOk());
    assertFalse(hasPassword(account, "password"));
    // the mailed password is the new one
    Matcher matcher = Pattern.compile("autogenerated password:\\s+(\\S+)").matcher(output.getOut());
    assertTrue(matcher.find(), output.getOut());
    assertTrue(hasPassword(account, matcher.group(1)));
  }

  @Test
  void passwordResetRejectsInvalidTokens() throws Exception {
    this.testData.account("user@example.com");
    this.mockMvc.perform(post("/api/users/password/reset").param("token", "not a token").with(csrf()))
        .andExpect(status().isBadRequest());
    this.mockMvc.perform(post("/api/users/password/reset")
        .param("token", this.timestampSigner.sign("nobody@example.com")).with(csrf()))
        .andExpect(status().isNotFound());
  }

  @Test
  void changeOwnPassword() throws Exception {
    Account account = this.testData.account("user@example.com");
    this.mockMvc.perform(put("/api/users/{uuid}/password", account.getUuid())
        .param("oldPassword", "wrong").param("newPassword", "new-password-123")
        .with(login(account)).with(csrf()))
        .andExpect(status().isBadRequest());
    this.mockMvc.perform(put("/api/users/{uuid}/password", account.getUuid())
        .param("oldPassword", "password").param("newPassword", "short")
        .with(login(account)).with(csrf()))
        .andExpect(status().isBadRequest());
    this.mockMvc.perform(put("/api/users/{uuid}/password", account.getUuid())
        .param("oldPassword", "password").param("newPassword", "new-password-123")
        .with(login(account)).with(csrf()))
        .andExpect(status().isOk());
    assertTrue(hasPassword(account, "new-password-123"));
  }

  @Test
  void passwordOfOthersIsChangedByAdminsOnly() throws Exception {
    Account account = this.testData.account("user@example.com");
    Account other = this.testData.account("other@example.com");
    Account admin = this.testData.admin();
    this.mockMvc.perform(put("/api/users/{uuid}/password", other.getUuid())
        .param("oldPassword", "password").param("newPassword", "new-password-123")
        .with(login(account)).with(csrf()))
        .andExpect(status().isForbidden());
    // admins need not know the old password
    this.mockMvc.perform(put("/api/users/{uuid}/password", other.getUuid())
        .param("oldPassword", "").param("newPassword", "new-password-123")
        .with(login(admin)).with(csrf()))
        .andExpect(status().isOk());
    assertTrue(hasPassword(other, "new-password-123"));
    this.mockMvc.perform(put("/api/users/{uuid}/password", other.getUuid())
        .param("oldPassword", "password").param("newPassword", "new-password-123").with(csrf()))
        .andExpect(status().isUnauthorized());
  }

  @Test
  void changeOwnEmail() throws Exception {
    Account account = this.testData.account("user@example.com");
    this.testData.account("taken@example.com");
    this.mockMvc.perform(put("/api/users/{uuid}/email", account.getUuid())
        .param("email", "new@example.com").param("password", "wrong")
        .with(login(account)).with(csrf()))
        .andExpect(status().isBadRequest());
    this.mockMvc.perform(put("/api/users/{uuid}/email", account.getUuid())
        .param("email", "not an email").param("password", "password")
        .with(login(account)).with(csrf()))
        .andExpect(status().isBadRequest());
    this.mockMvc.perform(put("/api/users/{uuid}/email", account.getUuid())
        .param("email", "taken@example.com").param("password", "password")
        .with(login(account)).with(csrf()))
        .andExpect(status().isBadRequest())
        .andExpect(status().reason(containsString("already taken")));
    this.mockMvc.perform(put("/api/users/{uuid}/email", account.getUuid())
        .param("email", "new@example.com").param("password", "password")
        .with(login(account)).with(csrf()))
        .andExpect(status().isOk());
    assertEquals("new@example.com", this.accountRepository.findFirstByUuid(account.getUuid()).getMail());
  }

  @Test
  void emailOfOthersIsChangedByAdminsOnly() throws Exception {
    Account account = this.testData.account("user@example.com");
    Account other = this.testData.account("other@example.com");
    this.mockMvc.perform(put("/api/users/{uuid}/email", other.getUuid())
        .param("email", "new@example.com").param("password", "password")
        .with(login(account)).with(csrf()))
        .andExpect(status().isForbidden());
  }

}
